swagger: "2.0"
info:
  description: "This is the swagger for the `NLW Valoriza`, an API built on the Next Level Week #06 event. Here you will find all the endpoints created on the mini course, and new ones, added on a improovement of the API"
  version: "1.1.1"
  title: "NLW Valoriza"
host: "localhost:3000"
basePath: "/nlw-valoriza"
tags:
- name: "Authentication"
  description: "NLW Valoriza authentication operations"
- name: "Users"
  description: "NLW Valoriza user operations."
- name: "Tags"
  description: "NLW Valoriza tag operations"
- name: "Compliments"
  description: "NLW Valoriza compliment operations"
schemes:
- "https"
- "http"
paths:
  /v1/login:
    post:
      tags:
      - "Authentication"
      summary: "Authenticate a user"
      description: "Authenticate users"
      operationId: "authenticateUsers"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "User credentials object"
        required: true
        schema:
          $ref: "#/definitions/Login"
      responses:
        "200":
          description: "successful operation"
          examples:
            application/json:
              access_token: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IndpbHRvbjJAZXhhbXBsZS5jb20iLCJpYXQiOjE2MjYxNzI5MjQsImV4cCI6MTYyNjI1OTMyNCwic3ViIjoiNDUzZWVhODctNzQxNi00MGY0LTllMzctZTA2NGU1ZmVkOTYzIn0.ApvFv5Dz6yPnURYfC7BBAEID2DHf08TG4Yllh49_VuA'
              expires_in: '1d'
  /v1/users:
    post:
      tags:
      - "Users"
      summary: "Create a new user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/User"
      responses:
        "201":
          description: "successful operation"
          schema:
            $ref: "#/definitions/UserList"
    put:
      tags:
      - "Users"
      summary: "Update a user"
      description: "This can only be done by a logged in Admin user."
      operationId: "updateUser"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: 'Ex: Bearer **eyJhbGciOiJSUzUxMiIsI...**'
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/UserEdit"
      responses:
        "204":
          description: "Successful operation"
    get:
      tags:
      - "Users"
      summary: "List all users"
      description: "This can only be done by the logged in user."
      operationId: "listUsers"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: 'Ex: Bearer **eyJhbGciOiJSUzUxMiIsI...**'
        required: true
        type: "string"
      - name: "name"
        in: "query"
        description: 'Ex: Adam'
        required: false
        type: "string"
      - name: "email"
        in: "query"
        description: 'Ex: adam@example.net'
        required: false
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            items:
              $ref: "#/definitions/UserList"
  /v1/users/{id}:
    get:
      tags:
      - "Users"
      summary: "Display data from a user"
      description: "This can only be done by the logged in user."
      operationId: "displayUser"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: 'Ex: Bearer **eyJhbGciOiJSUzUxMiIsI...**'
        required: true
        type: "string"
      - in: "path"
        name: "id"
        description: "Ex: b14f4379-1293-44fd-ad14-5de85bedd535"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/UserList"
    delete:
      tags:
      - "Users"
      summary: "Update a user"
      description: "This can only be done by the logged in user."
      operationId: "deleteUser"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: 'Ex: Bearer **eyJhbGciOiJSUzUxMiIsI...**'
        required: true
        type: "string"
      - in: "path"
        name: "id"
        description: "Ex: b14f4379-1293-44fd-ad14-5de85bedd535"
        required: true
        type: "string"
      responses:
        "204":
          description: "successful operation"
  /v1/users/password:
    patch:
      tags:
      - "Users"
      summary: "Update logged in user password"
      description: "This can only be done by the logged in user."
      operationId: "UpdateUserPassword"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Ex: Bearer **eyJhbGciOiJSUzUxMiIsI...**"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "Created user object"
        required: true
        schema:
          $ref: "#/definitions/PasswordEdit"
      responses:
        "200":
          description: "successful operation"
  /v1/tags:
    post:
      tags:
      - "Tags"
      summary: "Create a new tag"
      description: "This can only be done by the logged in user."
      operationId: "createTag"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Ex: Bearer **eyJhbGciOiJSUzUxMiIsI...**"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "New tag object"
        required: true
        schema:
          $ref: "#/definitions/Tag"
      responses:
        "201":
          description: "successful operation"
          schema:
            $ref: "#/definitions/CreateTags"
    get:
      tags:
      - "Tags"
      summary: "List all tags"
      description: "This can only be done by the logged in user."
      operationId: "listTag"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Ex: Bearer **eyJhbGciOiJSUzUxMiIsI...**"
        required: true
        type: "string"
      responses:
        default:
          description: "successful operation"
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/ListTags"
  /v1/tags{id}:
    delete:
      tags:
      - "Tags"
      summary: "Create a new tag"
      description: "This can only be done by the logged in user."
      operationId: "deleteTag"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Ex: Bearer **eyJhbGciOiJSUzUxMiIsI...**"
        required: true
        type: "string"
      - in: "path"
        name: "id"
        description: "Ex: b14f4379-1293-44fd-ad14-5de85bedd535"
        required: true
        type: "string"
      responses:
        "204":
          description: "Successful operation"
  /v1/compliments:
    post:
      tags:
      - "Compliments"
      summary: "Create a new compliment"
      description: "This can only be done by the logged in user."
      operationId: "createCompliment"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Ex: Bearer **eyJhbGciOiJSUzUxMiIsI...**"
        required: true
        type: "string"
      - in: "body"
        name: "body"
        description: "New tag object"
        required: true
        schema:
          $ref: "#/definitions/Compliments"
      responses:
        "201":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/CreateCompliment"
  /v1/compliments/{id}:
    delete:
      tags:
      - "Compliments"
      summary: "Delete a compiment"
      description: "This can only be done by the logged in user."
      operationId: "deleteCompliment"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Ex: Bearer **eyJhbGciOiJSUzUxMiIsI...**"
        required: true
        type: "string"
      - in: "path"
        name: "id"
        description: "A compliment ID. Ex: 2234537c-a01b-4ceb-b3b6-65cb825190f1"
        required: true
        type: "string"
      responses:
        "204":
          description: "Successful operation"
  /v1/compliments/sent:
    get:
      tags:
      - "Compliments"
      summary: "List sent compliments by logged in user"
      description: "This can only be done by the logged in user."
      operationId: "listSentCompliments"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Ex: Bearer **eyJhbGciOiJSUzUxMiIsI...**"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SendReceiveCompliments"
  /v1/compliments/received:
    get:
      tags:
      - "Compliments"
      summary: "List received compliments by logged in user"
      description: "This can only be done by the logged in user."
      operationId: "listRecivedCompliments"
      produces:
      - "application/json"
      parameters:
      - name: "Authorization"
        in: "header"
        description: "Ex: Bearer **eyJhbGciOiJSUzUxMiIsI...**"
        required: true
        type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/SendReceiveCompliments"
definitions:
  Login:
    type: "object"
    properties:
      email:
        type: "string"
        example: "example@example.com"
      password:
        type: "string"
        example: "1234"
    xml:
      name: "Login"
  User:
    type: "object"
    properties:
      name:
        type: "string"
        example: "Example"
      email:
        type: "string"
        example: "example@example.com"
      password:
        type: "string"
        example: "1234"
      admin:
        type: "boolean"
        default: false
    xml:
      name: "User"
  UserEdit:
    type: "object"
    properties:
      id:
        type: "string"
        example: "9f60dffb-63a0-4b41-9096-69d86a905a9d"
      name:
        type: "string"
        example: "Example"
      email:
        type: "string"
        example: "example@example.com"
      admin:
        type: "boolean"
        example: "true"
    xml:
      name: "UserEdit"
  UserList:
    type: "object"
    properties:
      id:
        type: "string"
        example: "b14f4379-1293-44fd-ad14-5de85bedd535"
      name:
        type: "string"
        example: "Victoria"
      email:
        type: "string"
        example: "example@example.com"
      admin:
        type: "boolean"
        example: true
      created_at:
        type: "string"
        default: "2021-06-24T09:23:31.000Z"
      updated_at:
        type: "string"
        default: "2021-06-24T09:23:31.000Z"
    xml:
      name: "User"
  PasswordEdit:
    type: "object"
    properties:
      password:
        type: "string"
        example: "2345"
    xml:
      name: "PaswwordEdit"
  Tag:
    type: "object"
    properties:
      name:
        type: "string"
        example: "Optimistic"
    xml:
      name: "Tag"
  ListTags:
    type: "object"
    properties:
      id:
        type: "string"
        example: "5cd0f878-917a-4335-9322-2bbd5b665f64"
      name:
        type: "string"
        example: "Optimistic"
      created_at:
        type: "string"
        example: "2021-06-23T09:31:50.000Z"
      updated_at:
        type: "string"
        example: "2021-06-23T09:31:50.000Z"
      name_custom:
        type: "string"
        example: "#optimistic"
    xml:
      name: "Tag"
  CreateTags:
    type: "object"
    properties:
      id:
        type: "string"
        example: "5cd0f878-917a-4335-9322-2bbd5b665f64"
      name:
        type: "string"
        example: "Optimistic"
      created_at:
        type: "string"
        example: "2021-06-23T09:31:50.000Z"
      updated_at:
        type: "string"
        example: "2021-06-23T09:31:50.000Z"
    xml:
      name: "CreateTags"
  Compliments:
    type: "object"
    properties:
      tag_id:
        type: "string"
        example: "774ce373-3e02-47d4-b465-6c3c93484eb5"
      user_receiver:
        type: "string"
        example: "774ce373-3e02-47d4-b465-6c3c93484eb5"
      message:
        type: "string"
        example: "You are fenomenal!"
    xml:
      name: "Compliments"
  CreateCompliment:
    type: "object"
    properties:
      id:
        type: "string"
        example: "9661734a-3d80-4a61-b550-087bb2167b88"
      user_sender:
        type: "string"
        example: "9661734a-3d80-4a61-b550-087bb2167b88"
      user_receiver:
        type: "string"
        example: "9661734a-3d80-4a61-b550-087bb2167b88"
      tag_id:
        type: "string"
        example: "9661734a-3d80-4a61-b550-087bb2167b88"
      message:
        type: "string"
        example: "You are an inspiration for the team!"
      created_at:
        type: "string"
        example: "2021-06-26T23:30:20.000Z"
    xml:
      name: "CreateCompliments"
  SendReceiveCompliments:
    type: "object"
    properties:
      id:
        type: "string"
        example: "774ce373-3e02-47d4-b465-6c3c93484eb5"
      user_sender:
        type: "string"
        example: "774ce373-3e02-47d4-b465-6c3c93484eb5"
      user_receiver:
        type: "string"
        example: "774ce373-3e02-47d4-b465-6c3c93484eb5"
      tag_id:
        type: "string"
        example: "774ce373-3e02-47d4-b465-6c3c93484eb5"
      message:
        type: "string"
        example: "You are fenomenal!"
      created_at:
        type: "string"
        example: "You are fenomenal!"
      userSender:
        $ref: "#/definitions/UserList"
      userReceiver:
        $ref: "#/definitions/UserList"
      tag:
        $ref: "#/definitions/ListTags"
    xml:
      name: "Compliments"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
